version: '2.1'
services:
  rp:
    build: ./producer
    restart: on-failure
    #volumes:
    #  - ./consumer:/app
    networks:
      - backend
    env_file:
      - ./.env
        #stdin_open: true
        #tty: true
    depends_on:
      db:
        condition: service_healthy
      rmq:
        condition: service_healthy
  rc:
    build: ./consumer
    restart: on-failure
    #volumes:
    #  - ./producer:/app
    networks:
      - backend
    env_file:
      - ./.env
        #stdin_open: true
        #tty: true
    depends_on:
      db:
        condition: service_healthy
      rmq:
        condition: service_healthy
  db:
    image: postgres:12.3-alpine
    restart: unless-stopped
    networks:
      - backend
    env_file:
      - ./.env
    #user: "1000:1000"
    #environment:
    #  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #  POSTGRES_USER: ${POSTGRES_USER}
    #  POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/pgdata-dc:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 15
  rmq:
    image: rabbitmq:3.8.5-management-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - backend
    #user: "1000:1000"
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./data/rmqdata-dc:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics check_alarms"]
      interval: 5s
      timeout: 5s
      retries: 15

networks:
  backend:
    driver: bridge
