kind: PersistentVolume
apiVersion: v1
metadata:
  name: makaba-reposter-rabbitmq-prod-pv
  labels:
    type: local
    app: makaba-reposter
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/wmw/git/blossom-bot/reposter/data/rmqdata-k8s-prod"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: makaba-reposter-prod
  name: makaba-reposter-rabbitmq-prod-pvc
  labels:
    app: makaba-reposter
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
