kind: PersistentVolume
apiVersion: v1
metadata:
  name: blossom-reposter-rabbitmq-staging-pv
  labels:
    type: local
    app: blossom-reposter
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/wmw/git/blossom-bot/reposter/data/rmqdata-k8s-staging"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: blossom-reposter-staging
  name: blossom-reposter-rabbitmq-staging-pvc
  labels:
    app: blossom-reposter
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
