kind: PersistentVolume
apiVersion: v1
metadata:
  name: blossom-reposter-pgdata-prod-pv
  labels:
    type: local
    app: blossom-reposter
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/wmw/git/blossom-bot/reposter/data/pgdata-k8s-prod"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: blossom-reposter-prod
  name: blossom-reposter-pgdata-prod-pvc
  labels:
    app: blossom-reposter
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
