apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: blossom-reposter-staging
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        name: ubuntu-2gb-nbg1-3
      containers:
        - name: postgres
          image: postgres:12.3-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: blossom-reposter-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: blossom-reposter-pgdata-staging-pvc

---

apiVersion: v1
kind: Service
metadata:
  namespace: blossom-reposter-staging
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
   app: postgres
